[package]
name = "coconut-rs"
version = "0.1.0"
authors = ["Jędrzej Stuczyński <andrew@nymtech.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = "0.4.0"
itertools = "0.10.0"
digest = "0.9.0"
rand_core = "0.6.1"

#[dependencies.zeroize]
#version = "1.2.0"
#features = ["zeroize_derive"]

sha2 = "0.9.3"
sha3 = "0.9.1"

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true
default-features = false

[dependencies.ff]
version = "0.9"
default-features = false

[dependencies.group]
version = "0.9"
default-features = false

[dev-dependencies.rand_core]
version = "0.6.1"
features = ["getrandom"]

[dev-dependencies]
criterion = "0.3"

[dev-dependencies.bincode]
version = "1"

[[bench]]
name = "benchmarks"
harness = false


# TODO: similarly to what dalek people are doing, include serde as feature?
