[package]
name = "coconut-rs"
version = "0.1.0"
authors = ["Jędrzej Stuczyński <andrew@nymtech.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = "0.4.0"
itertools = "0.10.0"
digest = "0.9.0"
#generic-array = "0.14.4"
rand_core = "0.6.1"

rand_chacha = "0.3.0"
sha3 = "0.9.1"

[dependencies.ff]
version = "0.9"
default-features = false

[dependencies.group]
version = "0.9"
default-features = false

[dev-dependencies]
criterion = "0.3"

[dev-dependencies.rand_core]
version = "0.6.1"
features = ["getrandom"]

[[bench]]
name = "benchmarks"
harness = false


# TODO: similarly to what dalek people are doing, include serde as feature?
