[package]
name = "coconut-rs"
version = "0.1.0"
authors = ["Jędrzej Stuczyński <andrew@nymtech.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = "0.4.0"

# TODO: similarly to what dalek people are doing, include serde as feature?

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false